spring:
  h2:
    console:
      enabled: true
      path: /h2-console
  datasource:
#    url: jdbc:h2:mem:test
    url: ${DATABASE_URL}
    driverClassName: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    spring.jpa.database-platform: org.hibernate.dialect.H2Dialect
  liquibase:
    change-log: classpath:db.changelog/liquibase-changeLog.xml

#logging:
#  config: classpath:log4j2-spring.xml

server:
  error:
    include-message: always
  port: ${PORT:5000}


music-services:
  urlMap:
    APPLE: localhost:8080
    YANDEX: ${YANDEX_URL:noyandex}
    SPOTIFY: ${SPOTIFY_URL:nospotify}
  actionsMap:
    URL: /authUrl
    CODE: /register
    EXPORT_PLAYLIST: /playlist
    IMPORT_PLAYLIST: /synchronize_tracks
    SEARCH_PLAYLIST: /playlistsList
    REGISTER_YANDEX: /register

